<ADSWorkspace Revision="46" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <Library Name="ads_serdes_ref_channel" />
        <Library Name="ads_quantum" />
        <Library Name="Simulation_Sequencing" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="Project_Q1_lib" />
        <Cell Name="Project_Q1_lib:cell_1" />
        <Log Name="netlist.log" />
        <Dataset Name="cell_1.ds" />
        <Data_Files Name="cell_1.ds" />
        <Data_Files Name="cell_1_data\logFile.txt" />
        <Cell Name="Project_Q1_lib:cell_2" />
        <ConfigFile Name="dds.cfg" />
        <Data_Display Name="cell_1.dds" />
        <Dataset Name="cell_2.ds" />
        <Data_Files Name="cell_2.ds" />
        <Data_Files Name="cell_2_data\logFile.txt" />
        <Data_Display Name="cell_2.dds" />
        <Log Name="search_history.log" />
        <Preferences Name="Project_Q1_lib_lay.prf" />
        <Log Name="readegs.log" />
        <Substrate Name="Project_Q1_lib:substrate1.subst" />
        <Dataset Name="cell_3_MomUW.ds" />
        <Data_Files Name="cell_3_MomUW.ds" />
        <Preferences Name="ads_rflib_lay.prf" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Dataset Name="cell_4.ds" />
        <Data_Files Name="cell_4.ds" />
        <Data_Files Name="cell_4_data\logFile.txt" />
        <Dataset Name="cell_5.ds" />
        <Data_Files Name="cell_5.ds" />
        <Data_Files Name="cell_5_data\logFile.txt" />
        <Log Name="momServer.log" />
        <Data_Files Name="cell_6_data\logFile.txt" />
        <Dataset Name="cell_3_MomRF.ds" />
        <Data_Files Name="cell_3_MomRF.ds" />
        <Dataset Name="cell_2_MomRF.ds" />
        <Data_Files Name="cell_2_MomRF.ds" />
        <Dataset Name="cell_5_MomRF.ds" />
        <Data_Files Name="cell_5_data\spare_removal.txt" />
        <Data_Files Name="cell_5_MomRF.ds" />
        <Cell Name="Project_Q1_lib:bonus 2" />
        <Data_Display Name="bonus 2.dds" />
        <Cell Name="Project_Q1_lib:bonus 1 part2" />
        <Data_Display Name="bonus 1 part2.dds" />
        <Cell Name="Project_Q1_lib:bonus 1" />
    </Workspace>
</ADSWorkspace>
